In [6]:
import numpy as np

In [11]:
np

<module 'numpy' from 'C:\\Users\\YSKIM\\anaconda3\\lib\\site-packages\\numpy\\__init__.py'>

In [17]:
"""
Numpy Array Attributes
"""

#Creatubg ab array
print(np.arange(3)) #stop
print(np.arange(2,5)) #start, stop
print(np.arange(1, 9, 2)) #start, stop, step

[0 1 2]
[2 3 4]
[1 3 5 7]


In [74]:
# Random number generator

arr1 = np.random.randint(10, size=(5))
print(arr1)

arr2 = np.random.randint(100, size=(3, 5))
print(arr2)

arr3 = np.random.randint(100, size=(3, 5, 2))
print(arr3)

[7 4 2 3 5]
[[91 19 51 56 53]
 [53  7 26 90 27]
 [ 4 75 53  1 77]]
[[[70 73]
  [72 55]
  [40 81]
  [47 19]
  [33  4]]

 [[ 6 79]
  [36 53]
  [59 22]
  [65 89]
  [95 34]]

 [[75 73]
  [71 58]
  [63 84]
  [65  6]
  [66 18]]]


In [85]:
# Atrributes

print("arr1.ndim = ", arr1.ndim)
print("arr2.ndim = ", arr2.shape)
print("arr2.size = ", arr2.size)

print("arr2.dtype = ", arr2.dtype)
print("arr2.itemsize = ", arr2.itemsize)

arr4 = np.array([1.5, 2.3, 3.4])
print("arr4.itemsize = ", arr4.itemsize)

print("arr2.nbytes = ", arr2.nbytes)

arr1.ndim =  1
arr2.ndim =  (3, 5)
arr2.size =  15
arr2.dtype =  int32
arr2.itemsize =  4
arr4.itemsize =  8
arr2.nbytes =  60


In [101]:
""" 
Subarrays as no-copy views
"""
np.random.seed(1)
arr = np.random.randint(10, size=(3, 4))
print(arr, '\n')

arr_sub = arr[:2, :2]
print(arr_sub, '\n')

arr_sub[0, 0] = -1
print(arr_sub, '\n')

print(arr)

[[5 8 9 5]
 [0 0 1 7]
 [6 9 2 4]] 

[[5 8]
 [0 0]] 

[[-1  8]
 [ 0  0]] 

[[-1  8  9  5]
 [ 0  0  1  7]
 [ 6  9  2  4]]


In [107]:
# copy()
np.random.seed(1)
arr = np.random.randint(10, size=(3, 4))
print(arr)

arr_sub = arr[:2, :2].copy()
print(arr_sub, '\n')

arr_sub[0, 0] = -1
print(arr_sub, '\n')

print(arr)

[[5 8 9 5]
 [0 0 1 7]
 [6 9 2 4]]
[[5 8]
 [0 0]] 

[[-1  8]
 [ 0  0]] 

[[5 8 9 5]
 [0 0 1 7]
 [6 9 2 4]]


In [113]:
"""
Reshaping of Arrays
"""

arr = np.arange(1, 10)
print(arr)

grid = arr.reshape(3, 3)
print(grid)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [118]:
#np.newaxis
arr = np.array([1, 2, 3])
print(arr)
print("arr.ndim = ", arr.ndim)
print("arr.shape = ", arr.shape)

arr_new = arr[:, np.newaxis]
print(arr_new)
print("arr_new.ndim = ", arr_new.ndim)
print("arr_new.shape = ", arr_new.shape)

[1 2 3]
arr.ndim =  1
arr.shape =  (3,)
[[1]
 [2]
 [3]]
arr_new.ndim =  2
arr_new.shape =  (3, 1)


In [121]:
"""
Array Concatenation
"""

arr_1 = np.array([1, 2, 3])
arr_2 = np.array([4, 5, 6])
arr_3 = np.array([7, 8, 9])

arr_total = np.concatenate([arr_1, arr_2, arr_3])
print(arr_total)

arr_total = np.vstack([arr_1, arr_2, arr_3])
print(arr_total)


[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [123]:
"""
Array Splitting
"""
arr = [1, 2, 3, 99, 99, 3, 2, 1]
print(arr)

arr_1, arr_2, arr_3 = np.split(arr, [2, 5])
print(arr_1, arr_2, arr_3)

[1, 2, 3, 99, 99, 3, 2, 1]
[1 2] [ 3 99 99] [3 2 1]
